# Generated by Django 5.2.3 on 2026-08-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.CharField(
                choices=[
                    ("focused_reading", "Focused Reading"),
                    ("indepth_guidance", "In-Depth Guidance"),
                    ("signature_guidance", "Signature Guidance"),
                    ("zoom_session", "Zoom Session"),
                ],
                max_length=20,
            ),
        ),
    ]
