# Generated by Django 5.2.3 on 2026-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_booking_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="time_slot",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
