# Generated by Django 5.2.3 on 2026-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_booking_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
